### ISSUE TITLE
Add more color variance to the false colour option?

### ISSUE THREAD

**Issue by SaxonRix** [sobotka/filmic-blender#14]
Hi, I'm from a video background so I'm quite used to using false colour to help expose my images. I've noticed that the current false colour layout within filmic blender is kind of confusing due to the use of cyan (a light colour, in the lower exposures) and similar green either side of the grey exposure.

Because of this, I thought that perhaps adjusting the colours of each EV to better match the false colour found in professional cameras such as the Arri Alexa would work better? The colours of each EV are more logical for users to grasp.

Example:
Black (clip)
Purple
Blue
Green
Dark Grey
Pink
Light Grey
Yellow
Red
White (clip)

**Comment by sobotka** [comment]
It was modeled loosely on the Alexa false colour chart, among others. There are smooth mixes between the colours which is why cyan appears, being slotted between blue and green.

That said, I completely disagree with some of Arri's choices, such as pink, which any experienced photographic peep knows exactly why it is there and, in my opinion, why it *shouldn't* be there.

The bottom line is that there isn't a single False Colour standard out there, and many ignore middle grey, which is rather important on the transform front.

Willing to hear opinions on this. While Arri does plenty of things very well, their false colour isn't one of the things I would consider a canonical baseline.

**Comment by SaxonRix** [comment]
That's fair enough. 

I used Arri as an example, but actually the colour examples I gave are based off of a marshall monitor, though they are mostly very similar. I'm used to seeing false colour on cameras/monitors that all shared a very similar chart. But looking at it now, I see that your chart is closer to that of the Flanders Scientific Monitors version.

I guess my only struggle with it then is just how close the underexposed green colour is to the overexposed green colour. That was the reason I suggested pink, not for skintones, but more just to differentiate the two sides a little more. That's probably just me though, but I thought it was worth mentioning from an average users perspective.

**Comment by sobotka** [comment]
> I guess my only struggle with it then is just how close the underexposed green colour is to the overexposed green colour.

This is something that has been (and is ongoing) a bit of a struggle. Hard to come up with a solution.

Green as the four stops around middle grey is tough to divide. Originally, there wasn't a middle grey band, so it wasn't an issue. Now with the band, folks have requested a method to deduce over and under, which is of course tricky when we think of blended colours.

It is something I would love to have a solution to. Ideas are welcome.

Pink ends up being a mash of colour if we do smooth interpolation, as well as my personal feeling it is *cough*.

Ideas?

**Comment by ro0mquy** [comment]
Maybe [this thoughts](http://matplotlib.org/users/colormaps.html) on choosing colormaps for visualizing data sets could be helpful.
